apiVersion: v1
kind: Pod
metadata:
  name: nginx-storage
  labels:
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: scratch-volume
          mountPath: /scratch # Default content directory
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["sleep 1000"]
      volumeMounts:
        - name: scratch-volume
          mountPath: /scratch
  volumes:
    - name: scratch-volume
      emptyDir:
        sizeLimit: 500Mi # This is temporary storage; it is deleted when the Pod stops

