apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: 8mblocal-claim2
  name: 8mblocal-claim2
  namespace: video-convertor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
