apiVersion: v1
kind: Service
metadata:
  labels:
    app: littlelink
  name: littlelink
spec:
  ports:
  - name: 8080-3000
    port: 8080
    protocol: TCP
    targetPort: 3000
  selector:
    app: littlelink
  type: LoadBalancer
status:
  loadBalancer: {}
